package main

import (
	"fmt"
	"nicotheowedding/api/whatsapp"
	"strings"
)

const (
	NomerAyah   = "6281265564468"
	NomerMami   = "6285261919124"
	NomerSayang = "6281370905656"
)

func main() {

	wa := whatsapp.NewWhatsappClient()

	//! YANG UDAH DI COMMENT BRTI UDAH DI GENERATE
	// mami
	_ = []string{
		// "Pdt Boas Malango",
		// "Pdt. Beres Panjaitan",
		// "GroupAngkatan PTASN 99",
		// "Group Sehati Sejiwa",
		// "Group.Pasombu Sihol",
		// "Group Imanuel Ministry", // typo mungkin: Group Imanuel Ministry
		// "Group Ministry Doa Ibu",
		// "Group Pendeta Se WKB",
		// "kel Jufri si mangunsong/Ranni Si debang",
		// "Kel Erna Nababan",
		// "Kel.Frenly Purba",
		// "Kel.Gredy Purba",
		// "Kel Chandro Tobing",
		// "Kel Sitanggan/Rut br Manurung",

		// "GMAHK Kisaran",
		// "GMAHK labuhan ruku",
		// "GMAHK Meranti",
		// "Kel bpk Silalahi/br hotang",
		// "Kel.Bpk Situngkir",
		// "Kel besar Pinoppar Op Tambok Sihombing",
		// "J.Lingga (Poli)",
		// "Ibu B. Hasibuan",
		// "H.Marbun",
		// "I.Simanjuntak",

		// "Daniel Capah",

		// "Kel bpk L Silalahi/br Sihotang",
		// "Kel Sitinjak/br silalahi",
		// "Kel tulang D. Marbun",

		// "R. Nainggolan",

		// "Orang tua kami Bapak Dasmen Sidebang",
		// "Kel Hotbin Naibaho",
		// "Kel Verry Aritonang",
		// "Orang tua kami Op Joel Manurung",
		// "Allen Rajagukguk/Susan Manurung",
		// "Kel Paul Siregar",
		// "Hellen Olmostead",
		// "Ronal Nitbani",
		// "Chris Purba",
		// "Pdt Sembi Naibaho",
		// "Pdt Toiman Siagian",
		// "Pdt. Lasno Kromowiryo Hutasoit",
		// "Pdt F. Manurung",
		// "Ibu Derbina Butajulu/br hombing",

		// "Pauji Sitompul",
		// "Sopar Siburian",
		// "K. Sijabat",
		// "Erita Siburian",
		// "kel. Bonatua Lumban Raja",
		// "kel. Bapak Nanang",
		// "Kel Ibu Diana Manurung",
		// "Ibu Andriana",
		// "Pdt Moritz Tumeu",
		// "Jimmyumangkun",
		// "dr Alvin Rantung",
		// "Pdt Boas Malango",
		// "Pdt. Beres Panjaitan",
		// "Group Angkatan PTASN 99",
		// "Group Sehati Sejiwa",
		// "Group Pasombu Sihol",
		// "Group Imanuel Ministry",
		// "Group Ministry Doa Ibu",
		// "Group Pendeta Se WKB",
		// "kel. Jufri Si Mangunsong / Ranni Si Debang",
		// "Kel Erna Nababan",
		// "Kel. Frenly Purba",
		// "Kel. Gredy Purba",
		// "Kel. Chandro Tobing",
		// "Kel Sitanggan / Rut br Manurung",
		// "Kel. Darius Sagala / br Torus",
		// "kel. Benny",
		// "Kel. Bpk Sihombing / br Simajuntak",
		// "dr Rudy",
		// "Kel. Jekson Silitonga",
		// "Ibu Marlen Jais",
		// "Rivaldo Pasaribu",
		// "kel. Bpk Fanny Sagala",
		// "Op Rey Simajuntak",
		// "Kel. Bpk Galingging / br Nainggolan",
		// "dr Alvin Sinaga",
		// "Mama Sheron",
		// "dr Natalina",
		// "Kel. Bpk Daniel",
		// "Kel. Adek kami Ak Ramedida",
		// "Kel. Bpk Sabar Hati Duha",
		// "Reine",
		// "kel. Yani",
		// "Kel. Bpk Siahaan",
		// "Kel. Bpk Siadari / br Hutagaol",
		// "Kel. Siburian",
		// "Evelin Siburian",
		// "Kel. Sipahutar",
		// "Kel. Bpk Pasaribu / br Siburian",
		// "Kel. Gultom / br Nainggolan",
		// "Josep Septianus",
		// "Kel. Maigoda",
		// "Kel. Dennis",
		// "Imam Mulyo Suyono",
		// "Kel. Batara Butar Butar",
		// "Jemaat Kayu Tanam",
		// "Darius Ayut",
		// "Bpk Yolanda",
		// "Kel. Bpk Galingging",
		// "Kel. Victor Taek",
		// "Kel. Bpk Dalima",
		// "Jemaat Semboja Sanggau",
		// "Kel. Hobby Simanungkalit / br Dolok Saribu",
		// "Kel. Bpk Aldo Simanungkalit",
		// "Jemaat Sintang",
		// "Jemaat Penyangkak",
		// "Kel. Tulang Bpk Sondang Sianturi",
		// "Kel. Tulang Albert Sianturi",
	}

	// sayang
	_ = []string{
		// "Adikku Yemima",
		// "Risa and Partner",
		// "Adel",
		// "Advent and Partner",
		// "Agusmanto Zaluku",
		// "Anlihong",
		// "Alin dan Partner",
		// "Andrew Panjaitan",
		// "Angel Simbolon",
		// "Angel (MIKA)",
		// "April Butar-butar",
		// "Mam Ari dan Keluarga",
		// "Arlike",
		// "Arum",
		// "Pdt. Arnold Ataupah",
		// "Ayu dan Suami",
		// "Bang Angga",
		// "Bang Abet",
		// "Bang Bill dan Istri",
		// "Bang Dani dan Istri",
		// "Bang David dan Istri",
		// "Bang Jeck",
		// "Josep Sirait",
		// "Bang Manampin dan Istri",
		// "Bang Tiger Siringo-ringo",
		// "Bang Zach dan Istri",
		// "Beriana dan Partner",
		// "Berto Manurung",
		// "Bang Adrian dan Partner",
		// "Pdt. Ronald dan Istri",
		// "Mam Tio dan Keluarga",
		// "Bou Melda Sidabutar dan Keluarga",
		// "Bram",
		// "Brenda dan Suami",
		// "Bu Amanda dan Keluarga",
		// "Bu Ami dan Keluarga",
		// "Ibu Endang dan Keluarga",
		// "Bu Susy dan Keluarga",
		// "Budi Simanjuntak",
		// "Pdt. Adib Budi Satriyo",

		// "Bang Elvan Naibaho",
		// "Bang Edi Nababan",
		// "Carmel Simbolon dan Partner",
		// "Chelsea dan Partner",
		// "Ka Chyntia Hasibuan",
		// "Cia dan Suami",
		// "Teh Cica dan Suami",
		// "Coach Martin",
		// "Dana Sinaga",
		// "Danai",
		// "Daniel Capah",
		// "David",
		// "Davinson Hutapea",
		// "Mam Debilly dan Keluarga",
		// "Ka Debita",
		// "Ka Debora dan Keluarga",
		// "Delviana",
		// "Devant Sinaga",
		// "Devra Suryaatmaja",
		// "Dewi Sihite",
		// "Dicky",
		// "Dinar",
		// "Sir Donn dan Keluarga",
		// "Doppak dan Partner",
		// "Tulang Dorlan",
		// "dr. Albert dan dr. Lily",
		// "dr. Afrah",
		// "dr. Amanda",
		// "dr. Devina",
		// "dr. Edi",
		// "dr. Gishelly",
		// "dr. Jeffrey",
		// "dr. Kennard",
		// "dr. Oktrian dan Keluarga",
		// "dr. Orlensia",
		// "dr. Silvia",
		// "dr. Wilma",
		// "dr. David",
		// "dr. Jeannte",
		// "dr. Natalia",
		// "dr. Stanley",

		// "dr. Jovita",
		// "dr. Stephanie",
		// "dr. Stefanny",
		// "dr. Bryan",
		// "dr. Jourdan",
		// "Novi",
		// "Ebiye Hasibuan",
		// "Edly",
		// "Elis",
		// "Elisabeth",
		// "Jessie Elita",
		// "Emely",
		// "Sahabatku Epik dan Partner",
		// "Erda Manurung",
		// "Mam Evelyn dan Keluarga",
		// "Ka Evi",
		// "Ade Fiola",
		// "Firman dan Istri",
		// "Kakak Fitri dan Partner",
		// "Florence dan Partner",
		// "Fragenia dan Partner",
		// "Gabby Ginting",
		// "Gabriella",
		// "Grace Damanik",
		// "Gheralyn dan Suami",
		// "Giatmi",
		// "Sahabatku Hakkel",
		// "Hartati Sembiring",
		// "Henock",
		// "Hosea",

		// "Angel Hutapea",
		// "Ibu Murni",
		// "Mam Ida dan Keluarga",
		// "Pra ku Indah",
		// "Inggrid (MIKA)",
		// "Irene",
		// "Irvan",
		// "Jane",
		// "Jassica dan Partner",
		// "Jeremy Panjaitan dan Partner",
		// "Jesika Humau",
		// "Junior Tampubolon dan Parrner",
		// "Ka Agnes Sinaga",
		// "Kakak Prinasti Anggi",
		// "Annisa dan Partner",

		// "Ka Ayu",
		// "Ka Ayu dan Keluarga",
		// "Ka Cahyarini",
		// "Ka Caroline Tupen dan Partner",
		// "Kak Conny",
		// "Kakakku Cyntia dan Partner",
		// "Kakakku Mama Richie dan abang",
		// "Ka Davia dan Suami",
		// "Ka Debby Sihombing",
		// "Ka Desi",
		// "Ka Devi dan Suami",
		// "Ka Devie Patana",
		// "Ka Dian",
		// "Ka Ardiana",
		// "Ka Erawati dan Abang",
		// "Ka Esta dan Keluarga",
		// "Ka Eva dan Suami",
		// "Ka Fadhila dan Partner",
		// "Ka Fanny Situmorang",
		// "Ka Eunike Feby dan Partner",
		// "Ka Ferci dan Suami",
		// "Ka Grace Hutajulu dan Partner",
		// "Ka Grentina",

		// "Ka Hanny Sirait",
		// "Ka Heppy dan Suami",
		// "Ka Heppy dan Suami (Klinik)",
		// "Ka Hesti dan Partner",
		// "Ka Inda Eva",
		// "Ka Irawati dan Suami",
		// "Ka Isma",
		// "Ka Karsih",
		// "Ka Lita Sri Wahyuni",
		// "Ka Maulina dan Suami",
		// "Ka Mei Tampubolon dan Suami",
		// "Ka Meilan dan Abang",
		// "Ka Melisa dan Suami",
		// "Ka Mercy",
		// "Ka Moni",
		// "Ka Nuke dan Suami",
		// "Ka Ayu Pratiwi",
		// "Ka Rebecca dan Suami",
		// "Ka Reena Pasaribu",
		// "Ka Rency (MIKA)",
		// "Ka Resvi dan Suami",
		// "Ka Rhika",
		// "Ka Rina dan Suami",
		// "Ka Nisrina dan Partner",
		// "Ka Riris dan Suami",
		// "Ka Rosita dan Partner",
		// "Ka Septa",
		// "Ka Shysillia dan Suami",
		// "Ka Silvia",
		// "Ka Christina Sirait dan Partner",
		// "Ka Tio Naibaho",
		// "Ka Tren dan Suami",
		// "Ka Ulil",
		// "Ka Vivi dan Abang",
		// "Ka Yusniar",
		// "Ka Destisa",
		// "Ketrin Sinaga",
		// "Sir Albert",
		// "Kevin Doloksaribu dan Istri",
		// "Ka Kiki Andryani dan Suami",
		// "Ka Kirana Sitepu",
		// "Nicholas Kodir",
		// "Krisna",
		// "Ka Yessi Sitepu",
		// "Ka Aosta",
		// "Komang dan Partner",
		// "Anton dan Partner",
		// "Ladys",
		// "Ka Laura Manik",
		// "Sahabatku Lely",
		// "Lidya",
		// "Ka Isa dan Suami",
		// "Sir Maju Simanjuntak dan Keluarga",
		// "Mam Mori Perangin-angin dan Keluarga",
		// "Tante Claudinna dan Keluarga",
		// "Mam Erna dan Keluarga",
		// "Mam Jeanny dan Keluarga",
		// "Mam Sherly dan Keluarga",
		// "Ibu Kumintar (Mami ku tersayang)",
		// "Mas Alfian",
		// "Mas Aca",
		// "Mas Budi",
		// "Mas Dany dan Partner",
		// "Mas Duwi dan Istri",
		// "Mas Edi dan Keluarga",
		// "Mas Putra dan Keluarga",
		// "Mam Masta Tambunan dan Keluarga",
		// "Regina",
		// "Mba Peni",
		// "Melda",
		// "Ka Melyn dan Keluarga",
		// "Bang Michael dan Istri",
		// "Michelle dan Pdt Daffin",
		// "Mam Mona dan Keluarga",
		// "Monica",
		// "Monica Sihite",
		// "Yuni",
		// "Nisah",
		// "Nanguda dan Uda Amran",
		// "Nantulang Sean",
		// "Naomi Simanjuntak",
		// "Natania",
		// "Nengchy",
		// "Ka Nike dan Partner",
		// "Nita dan Suami",
		// "Sahabatku Nia Laurenza",
		// "Bang November",
		// "Novia",
		// "Ka Nindy dan Suami",
		// "Ochi Simbolon",
		// "Oktri",
		// "Ossye",
		// "Pak Agoes dan Keluarga",
		// "Pak Dedy dan Keluarga",
		// "Pak Haryadi dan Keluarga",
		// "Pak Herman dan Keluarga",
		// "Pak Jones dan Keluarga",
		// "Tim UGD RS PIK",
		// "Pak Sugiarto dan Keluarga",
		// "Richard Pasaribu",
		// "Pasri Simbolon",
		// "Pisga",
		// "Pak Tan",
		// "Rahel Sitompul",
		// "Rahel Hutasoit",
		// "Ririn dan Partner",
		// "Reyner",
		// "Ririn",
		// "Romauli dan Partner",
		// "Rosalinda dan Partner",
		// "Ka Cindy dan Suami",
		// "Sabrina Sihotang",
		// "Sabrina Silalahi",
		// "Dina Safitri",
		// "Gidion Sagala",
		// "Tante Sarah",
		// "Sartika",
		// "Ka Shanny",
		// "Sir Elon dan Keluarga",
		// "Geo Sitepu dan Partner",
		// "Steven",
		// "Bou Cantik dan Amangboru",
		// "Syeba dan Partner",
		// "Tante Tabitha",
		// "Tamara",
		// "Tante Cantik dan Uda (Tante Erna)",
		// "Tarisa",
		// "Twinku Mama Sean Dan Suami",
		// "Teh Nika",
		// "Tere",
		// "Thomson Simbolon",
		// "Tulang Sevent dan Nantulang Marbun",
		// "Tabitha",
		// "Ryan",
		// "Sir Untung dan Keluarga",
		// "Pdt Vacto Siringo-ringo dan Keluarga",
		// "Velin",
		// "Ryanti Vianica dan Suami",
		// "Wahyu dan Keluarga",
		// "Welmy dan Partner",
		// "Jhon William",
		// "Wulan Marbun",
		// "Yehuda",
		// "Yohana Napitupulu",
		// "Yolanda Sinaga",
		// "Yucta Manik",
		// "Mbak Yunis",
		// "Zakharia",
	}

	// ayah
	list := []string{
		// "Pdt. Sugih Sitorus",
		// "Pdt. Binsar Sagala",
		// "Panahatan Doloksaribu",
		// "Pdt. Sutrisno Tjakrapawira",
		// "Pdt. Ronny Wenas",
		// "Richard Panjaitan",
		// "Pdt. Suciyatno",
		// "Pdt. Leonard Mamentu",
		// "Pdt. Albertho Tulaelessy",
		// "Pdt. Victor Joe Sinaga",
		// "Parulian Sihotang",
		// "Pdt. Sonny Sipayung",
		// "Pdt. Jimmy Havelaar",
		// "Pdt. Eben Ezer Sembiring",
		// "Morgan Siagian",
		// "Pdt. Sanny Manoppo",
		// "Pdt. Yohanes Doloksaribu",
		// "David Soputra",
		// "Pdt. Joram Hutagaol",
		// "Pdt. Maysonny Situmorang",
		// "Hisar Simalango",
		// "Edison Gurusinga",
		// "Johanes Handriadi",
		// "Darwin Frenly Malau",

		// "Executive Secretary WIUM",
		// "WIUM Field Secretary",
		// "Direktur AM/AMR'25 seUIKB",
	}

	for _, item := range list {

		// Step 1: Ganti titik dengan spasi
		item = strings.ReplaceAll(item, ".", " ")

		// Step 2: Trim untuk menghilangkan spasi ekstra
		item = strings.TrimSpace(item)

		// Step 3: Ganti semua spasi menjadi %20
		item = strings.ReplaceAll(item, " ", "%20")

		err := wa.SendPersonalMessage(NomerAyah, fmt.Sprintf(
			`
		Shalom dan salam hangat,

		Dengan penuh sukacita dan ucapan syukur kepada Tuhan Yesus Kristus, kami mengundang Bapak/Ibu/Saudara/i terkasih untuk hadir dan memberikan doa restu di hari bahagia kami, saat kami mengikat janji suci pernikahan:

		Nicolas & Theofani

		📆 Selasa, 8 Juli 2025

		✝ Ibadah Pemberkatan Pernikahan
		🕘 Pukul 09.00 WIB – Selesai
		📍 Gereja Masehi Advent Hari Ketujuh (GMAHK) Tanjungbalai

		💍 Acara Adat dan Resepsi
		🕛 Pukul 12.00 WIB – Selesai
		📍 Aula Pertemuan Katolik Teluk Ketapang, Tanjungbalai

		Kami percaya bahwa perjalanan ini adalah karya kasih Tuhan yang begitu indah. Dan pada hari itu, kami berharap dapat berbagi sukacita bersama Bapak/Ibu/Saudara/i yang telah menjadi bagian penting dalam hidup kami.

		Informasi lebih lengkap mengenai acara pernikahan kami dapat diakses melalui tautan berikut:
		🌐 https://nicotheoweddinginvitation.netlify.app/?guest_name=%s

		Kehadiran dan doa restu Anda merupakan anugerah besar bagi kami. Kiranya Tuhan senantiasa melimpahkan kesehatan, kebahagiaan, dan damai sejahtera bagi Bapak/Ibu/Saudara/i di setiap langkah kehidupan.

		Dengan kasih,
		Nico & Fani
	`, item))
		if err != nil {
			fmt.Println("fail to SendPersonalMessage because of " + err.Error())
		} else {
			fmt.Println("success to SendPersonalMessage of " + item)
		}
	}

}
